- name: Updating localhost
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '^((127\.0\.0\.1|::1)\s.*localhost\.).*$'
    replace: '\g<1>{{ ansible_domain }}'
  when: ansible_domain

- name: Updating IPv4 Host Name
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^{{ ansible_default_ipv4.address }}\s.*$'
    line: "{{ ansible_default_ipv4.address }}\t\t{{ ansible_fqdn }} {{ ansible_hostname }}"
  when: ansible_default_ipv4
