- name: Updating localhost
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '^((127\.0\.0\.1|::1)\s.*localhost\.).*$'
    replace: '\g<1>{{ ansible_facts["domain"] }}'
  when: ansible_facts['domain'] | length > 0

- name: Updating IPv4 Host Name
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^{{ ansible_facts["default_ipv4"]["address"] }}\s.*$'
    line: "{{ ansible_facts['default_ipv4']['address'] }}\t\t{{ ansible_facts['fqdn'] }} {{ ansible_facts['hostname'] }}"
  when: ansible_facts['default_ipv4']['address'] | length > 0
