- name: Configuring SSH
  ansible.builtin.include_role:
    name: common
    tasks_from: ssh
  vars:
    ssh_type: ed25519 # noqa: var-naming
    ssh_authorized_keys: '{{ authorized_keys }}' # noqa: var-naming

- name: Installing sudo
  community.general.pkgng:
    name: sudo
    state: present

- name: Updating sudoers
  ansible.builtin.replace:
    path: /usr/local/etc/sudoers
    regexp: '^#\s?(%wheel ALL=\(ALL:ALL\) ALL)$'
    replace: '\g<1>'
