- name: Configuring ntpd
  notify:
    - restart ntpd
  block:
    - name: Installing ntp.conf
      ansible.builtin.copy:
        src: files/ntp.conf
        dest: /etc/
        mode: '0644'

    - name: Enabling ntpd in rc.conf
      community.general.sysrc:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
      with_items:
        - { name: ntpd_enable, value: 'YES' }
        - { name: ntpd_sync_on_start, value: 'YES' }
      notify:
        - sort rc.conf
