zfs_enable="YES"
zfskeys_enable="YES"
syslogd_flags="-ss"
blanktime="NO"
moused_nonedefault_enable="NO"
sendmail_enable="NONE"
dumpdev="AUTO"
update_motd="NO"
dynamic_motd="YES"
motd_sitename="quuxotic.net"
