all:
  hosts:
    # anchorage:
    #   ansible_host: anchorage.quuxotic.net

    bailiwick:
      ansible_host: bailiwick.quuxotic.net

    beastie:
      ansible_host: beastie.quuxotic.net

    pipebanger:
      ansible_host: pipebanger.quuxotic.net

jails:
  hosts:
    net:
      ansible_jail_host: bailiwick.quuxotic.net
      ansible_connection: sshjail

    kdc:
      ansible_jail_host: bailiwick.quuxotic.net
      ansible_jail_privilege_escalation: none
      ansible_connection: jailexec

    fs:
      ansible_jail_host: bailiwick.quuxotic.net
      ansible_connection: jailexec
