freebsd_hosts:
  hosts:
    # anchorage:
    #   ansible_host: anchorage.quuxotic.net
    bailiwick:
      ansible_host: bailiwick.quuxotic.net
    beastie:
      ansible_host: beastie.quuxotic.net
    pipebanger:
      ansible_host: pipebanger.quuxotic.net

freebsd_jails:
  children:
    bailiwick_jails:
      hosts:
        fs:
        kdc:
        net:
      vars:
        ansible_host: bailiwick.quuxotic.net
  vars:
    ansible_connection: jailexec
