all:
  hosts:
    # anchorage:
    #   ansible_host: anchorage.quuxotic.net

    bailiwick:
      ansible_host: bailiwick.quuxotic.net

    beastie:
      ansible_host: beastie.quuxotic.net

    pipebanger:
      ansible_host: pipebanger.quuxotic.net
